<?php

namespace mythdigital\bundles\events;

use craft\commerce\elements\Order;
use mythdigital\bundles\models\Bundle;
use craft\commerce\models\OrderAdjustment;
use craft\events\CancelableEvent;

/**
 * Class BundleAdjustmentsEvent
 *
 * @author Myth Digital
 * @since 1.0.0
 */
class BundleAdjustmentsEvent extends CancelableEvent
{
    // Properties
    // =========================================================================

    /**
     * @var Order The order the discount generated the adjustments for. Do not mutate.
     */
    public $order;

    /**
     * @var Bundle The bundle that matched.
     */
    public $bundle;

    /**
     * @var OrderAdjustment[] The adjustments generated by the discount.
     */
    public $adjustments;
}
